# import and prepare data.

In [1]:
import numpy as np
import pickle
import pandas as pd

load data from Mercado et al., drop outlier

In [3]:
df = pd.read_csv('properties.csv')
# we remove row 48225 since it is an outlier for void fraction feature  # can be seen by df[df[' void fraction [widom]'] > 1]
df = df.drop(48225)
df.head()

dimensions  bond type                                  name  \
0           2      amide   linker91_CO_linker87_NH_hcb_relaxed   
1           2      amide   linker91_CO_linker88_NH_hcb_relaxed   
2           2      amide    linker91_CO_linker7_NH_hcb_relaxed   
3           2      amide    linker91_CO_linker8_NH_hcb_relaxed   
4           2      amide   linker91_CO_linker10_NH_hcb_relaxed   

    void fraction [widom]   supercell volume [A^3]   density [kg/m^3]  \
0                0.900120             49204.128057         260.213228   
1                0.879234             49390.074419         297.963387   
2                0.858269             50036.985281         289.397249   
3                0.857065             49135.924517         370.063633   
4                0.858016             49540.680132         367.040151   

    heat desorption high P [kJ/mol]   heat desorption error high P [kJ/mol]  \
0                          10.95162                                0.315667   
1                          11.81756                                0.478028   
2                          11.86378                                0.140491   
3                          12.48842                                0.823728   
4                          12.25924                                0.191371   

    absolute methane uptake high P [molec/unit cell]  \
0                                           233.2892   
1                                           250.6164   
2                                           255.1510   
3                                           257.3368   
4                                           253.2620   

    absolute methane uptake error high P [molec/unit cell]  ...   num sulfur  \
0                                           2.789059        ...            0   
1                                           3.464625        ...            0   
2                                           0.921036        ...            0   
3                                           2.377728        ...            0   
4                                           3.177484        ...            0   

    num silicon   vertices   edges   genus  \
0             0          1       1       0   
1             0          1       1       0   
2             0          1       1       0   
3             0          1       1       0   
4             0          1       1       0   

    largest included sphere diameter [A]   largest free sphere diameter [A]  \
0                               17.19014                           15.64961   
1                               17.34916                           15.76943   
2                               16.84032                           15.61907   
3                               13.93085                           12.32167   
4                               16.06923                           13.48791   

    largest included sphere along free sphere path diameter [A]  \
0                                           17.19004              
1                                           17.34916              
2                                           16.84024              
3                                           13.93085              
4                                           16.06921              

    absolute methane uptake high P [v STP/v]  \
0                                 176.160498   
1                                 188.532073   
2                                 189.461764   
3                                 194.588962   
4                                 189.943092   

    absolute methane uptake low P [v STP/v]  
0                                 20.988007  
1                                 22.643282  
2                                 22.566022  
3                                 27.373459  
4                                 24.774006  

[5 rows x 53 columns]

define new feature as density of elements

In [4]:
elements = ['carbon', 'fluorine', 'hydrogen', 'nitrogen', 'oxygen', 'sulfur', 'silicon']
for el in elements:
    df["density of " + el] = df[' num ' + el] / df[' supercell volume [A^3]']
df.head()

dimensions  bond type                                  name  \
0           2      amide   linker91_CO_linker87_NH_hcb_relaxed   
1           2      amide   linker91_CO_linker88_NH_hcb_relaxed   
2           2      amide    linker91_CO_linker7_NH_hcb_relaxed   
3           2      amide    linker91_CO_linker8_NH_hcb_relaxed   
4           2      amide   linker91_CO_linker10_NH_hcb_relaxed   

    void fraction [widom]   supercell volume [A^3]   density [kg/m^3]  \
0                0.900120             49204.128057         260.213228   
1                0.879234             49390.074419         297.963387   
2                0.858269             50036.985281         289.397249   
3                0.857065             49135.924517         370.063633   
4                0.858016             49540.680132         367.040151   

    heat desorption high P [kJ/mol]   heat desorption error high P [kJ/mol]  \
0                          10.95162                                0.315667   
1                          11.81756                                0.478028   
2                          11.86378                                0.140491   
3                          12.48842                                0.823728   
4                          12.25924                                0.191371   

    absolute methane uptake high P [molec/unit cell]  \
0                                           233.2892   
1                                           250.6164   
2                                           255.1510   
3                                           257.3368   
4                                           253.2620   

    absolute methane uptake error high P [molec/unit cell]  ...  \
0                                           2.789059        ...   
1                                           3.464625        ...   
2                                           0.921036        ...   
3                                           2.377728        ...   
4                                           3.177484        ...   

    largest included sphere along free sphere path diameter [A]  \
0                                           17.19004              
1                                           17.34916              
2                                           16.84024              
3                                           13.93085              
4                                           16.06921              

    absolute methane uptake high P [v STP/v]  \
0                                 176.160498   
1                                 188.532073   
2                                 189.461764   
3                                 194.588962   
4                                 189.943092   

    absolute methane uptake low P [v STP/v]  density of carbon  \
0                                 20.988007           0.007316   
1                                 22.643282           0.007289   
2                                 22.566022           0.008634   
3                                 27.373459           0.007327   
4                                 24.774006           0.007267   

   density of fluorine  density of hydrogen  density of nitrogen  \
0                  0.0             0.004390             0.002927   
1                  0.0             0.004373             0.002916   
2                  0.0             0.007195             0.002878   
3                  0.0             0.002931             0.004396   
4                  0.0             0.002907             0.004360   

   density of oxygen  density of sulfur  density of silicon  
0           0.001463                0.0                 0.0  
1           0.002916                0.0                 0.0  
2           0.001439                0.0                 0.0  
3           0.004396                0.0                 0.0  
4           0.004360                0.0                 0.0  

[5 rows x 60 columns]

get feature matrix and target vector

In [5]:
features = [' void fraction [widom]', ' density [kg/m^3]', ' largest included sphere diameter [A]', ' largest free sphere diameter [A]', ' surface area [m^2/g]',
            'density of carbon', 'density of fluorine', 'density of hydrogen', 'density of nitrogen', 'density of oxygen', 'density of sulfur', 'density of silicon']
print("# features: ", len(features))

# features:  12


In [6]:
y = df[' deliverable capacity [v STP/v]'].values
print("shape of Y: ", np.shape(y))
y

shape of Y:  (69839,)


array([155.17249134, 165.88879162, 166.8957419 , ..., 161.97256899,
       155.38761768, 155.48070341])

In [7]:
X = df[features].values
print("shape of X: ", np.shape(X))
X

shape of X:  (69839, 12)


array([[9.00120000e-01, 2.60213228e+02, 1.71901400e+01, ...,
        1.46329186e-03, 0.00000000e+00, 0.00000000e+00],
       [8.79234000e-01, 2.97963387e+02, 1.73491600e+01, ...,
        2.91556556e-03, 0.00000000e+00, 0.00000000e+00],
       [8.58269000e-01, 2.89397249e+02, 1.68403200e+01, ...,
        1.43893561e-03, 0.00000000e+00, 0.00000000e+00],
       ...,
       [8.85007000e-01, 2.59378413e+02, 1.60821800e+01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [7.37251000e-01, 5.14847059e+02, 1.15594900e+01, ...,
        1.43384585e-03, 0.00000000e+00, 0.00000000e+00],
       [7.77576000e-01, 5.01030978e+02, 1.15140800e+01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

Min-Max normalize the features so that they lie in $[0, 1]$. this is ok to do over all data as opposed to just training because in BO we will compute the cheap features of every COF in the database.

In [8]:
for i in range(np.shape(X)[1]):
    X[:, i] = (X[:, i] - np.min(X[:, i])) / (np.max(X[:, i]) - np.min(X[:, i]))
    print("feature", i, " in [", np.min(X[:, i]), ",", np.max(X[:, i]), "]")
X

feature 0  in [ 0.0 , 1.0 ]
feature 1  in [ 0.0 , 1.0 ]
feature 2  in [ 0.0 , 1.0 ]
feature 3  in [ 0.0 , 1.0 ]
feature 4  in [ 0.0 , 1.0 ]
feature 5  in [ 0.0 , 1.0 ]
feature 6  in [ 0.0 , 1.0 ]
feature 7  in [ 0.0 , 1.0 ]
feature 8  in [ 0.0 , 1.0 ]
feature 9  in [ 0.0 , 1.0 ]
feature 10  in [ 0.0 , 1.0 ]
feature 11  in [ 0.0 , 1.0 ]


array([[0.90081723, 0.20318731, 0.15909104, ..., 0.15284004, 0.        ,
        0.        ],
       [0.8775969 , 0.23561078, 0.16100571, ..., 0.30452924, 0.        ,
        0.        ],
       [0.85428875, 0.22825336, 0.15487906, ..., 0.15029605, 0.        ,
        0.        ],
       ...,
       [0.88401512, 0.20247029, 0.14575075, ..., 0.        , 0.        ,
        0.        ],
       [0.71974518, 0.42189136, 0.0912957 , ..., 0.14976442, 0.        ,
        0.        ],
       [0.7645771 , 0.41002478, 0.09074894, ..., 0.        , 0.        ,
        0.        ]])

In [10]:
with open('inputs_and_outputs.pkl', 'wb') as file:
    pickle.dump({'X': X, 'y': y, 'features': features}, file)